### ISSUE TITLE
mvn install失败 

### ISSUE THREAD

**Issue by fqtyfz** [codefollower/Lealone#76]
[ERROR] codefollower\Lealone\lealone-cluster\src\main\java\org\lealone\cluster\streaming\StreamSession.java:[280,116] 错误: 不兼容的类
型: List<StorageMap<? extends Object,? extends Object>>无法转换为Collection<? extends StorageMap<Object,Object>>

**Comment by fqtyfz** [comment]
前面的错误过了，但又有新的了。
[ERROR] \codefollower\Lealone\lealone-storage\src\main\java\org\lealone\storage\rtree\RTreeMap.java:[55,13] 错误: 名称冲突: RTreeMap 中
的 get(SpatialKey) 覆盖的方法的疑符与另一个方法的相同, 但两者均不覆盖对方

**Comment by codefollower** [comment]
JDK是什么版本？至少需要1.7

不一定要install的，可以用mvn package -Dmaven.test.skip=true试试
如果要导到Eclipse中，直接mvn eclipse:eclipse

**Comment by fqtyfz** [comment]
mvn package -Dmaven.test.skip=true
这样也过不去，on project lealone-storage: Compilation failure

**Comment by codefollower** [comment]
把RTreeMap.java:[55,13] 中的@Override注释掉看看。

我用的是1.8，mvn install和package都能通过，导到Eclipse中也没报错

**Comment by codefollower** [comment]
如果还出错，就mvn clean一下
